/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package indexReader;



import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.util.ArrayList;
import java.util.Random;

public class App {

    public static void main(String[] args) {
        App main = new App();
        if(args[0].equals("-avg"))
            main.findAverage(args[1]);
        else if(args[0].equals("-record"))
            main.findRecord(args[1],args[2]);
        else {
            System.out.println("Please try again with following options"
                                + "\n" + "-avg : find average(path required)"
                                + "\n" + "-record : find record with in size of the given number(path and number required)");
            return;
        }
    }

        private void findRecord(String inputpath, String recordNum) {
        Reader in = null;
        Random ran = new Random();
        ArrayList <String> found = new ArrayList<String>();
        try {
            in = new FileReader(inputpath);
            CSVParser parser = CSVFormat.EXCEL.parse(in);

            for (CSVRecord record : parser) {
                if(record.size() == Integer.valueOf(recordNum))
                    found.add(record.toString());
            }

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        for(int i = 0; i < 10; i++)
        {
            System.out.println(found.get(ran.nextInt(found.size()-1)));
        }


    }

    public void findAverage(String inputpath) {
        try {
            int recordCounter = -1;
            int recordSizeSum = 0;
            Reader in = new FileReader(inputpath);

            CSVParser parser = CSVFormat.EXCEL.parse(in);

            for (CSVRecord record : parser) {
                    recordCounter++;
                    recordSizeSum = recordSizeSum + record.size();
            }
            int average = recordSizeSum/recordCounter;
            System.out.println("Average : " + average);

            in = new FileReader(inputpath);
            CSVParser parser2 = CSVFormat.EXCEL.parse(in);
            long numerator = 0;
            int denominator = recordCounter-1;
            for (CSVRecord record : parser2) {
                int sigma = record.size()-average;
                sigma = sigma * sigma;
                numerator = numerator + sigma;
                //System.out.println(numerator);
            }

            double std = Math.sqrt(numerator/denominator);
            System.out.println("Standard Deviation : " + std);


            } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }
}
