/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package indexReader;



import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.util.List;

public class Main {
    private static String path;
    public static void main(String[] args) {
        Main main = new Main();
        if (args[0].equals("-p"))
            path = args[1];

        if(args[0].equals("-avg"))
            main.findAverage(args[1]);
        else if(args[0].equals("-record"))
            main.findRecord(args[1],args[2]);
        else if (args[0].equals("-commit")) {
            CommitMSGFinder msg = new CommitMSGFinder(args[1]);
        } else if (args[0].equals("-issue")) {
            IssueDocGenerator issue = new IssueDocGenerator(args[1]);
        }
        else {
            System.out.println("Please try again with following options"
                                + "\n" + "-avg : find average(path required)"
                                + "\n" + "-record : find record with in size of the given number(path and number required)");
            return;
        }
    }

    private void findRecord(String inputpath, String recordNum) {



    }

    public void findAverage(String inputpath) {
        try {
            int recordCounter = -1;
            int recordSizeSum = 0;
            Reader in = new FileReader(inputpath);

            CSVParser parser = CSVFormat.EXCEL.parse(in);

            for (CSVRecord record : parser) {
                    recordCounter++;
                    recordSizeSum = recordSizeSum + record.size();
            }
            int average = recordSizeSum/recordCounter;
            System.out.println("Average : " + average);


            in = new FileReader(inputpath);
            CSVParser parser2 = CSVFormat.EXCEL.parse(in);
            List<CSVRecord> list = parser2.getRecords();
            long numerator = 0;
            int denominator = recordCounter-1;
            int maxCount = 0, mode = 0;
            for (CSVRecord record : list) {
                int count = 0;
                int sigma = record.size() - average;
                sigma = sigma * sigma;
                numerator = numerator + sigma;
//                for (CSVRecord record2 : list) {
//                    if (record.size() == record2.size())
//                        ++count;
//                    if (count > maxCount) {
//                        maxCount = count;
//                        mode = record.size();
//                    }
//
//                    System.out.println(mode);
//                }
            }
                double std = Math.sqrt(numerator / denominator);
                System.out.println("Standard Deviation : " + std
                                    + "\n" +"Total Count : " + recordCounter);

        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }
}
